spring:
  config:
    activate:
      on-profile: default
  redis:
    host: localhost
    port: 6379
  application:
    name: "takehome"
    request:
      limit:
        authenticated: 20
        unauthenticated: 5
        time: 1
---
spring:
  config:
    activate:
      on-profile: docker
  redis:
    host: redis-service
    port: 6379
  application:
    name: "takehome"
    request:
      limit:
        authenticated: 20
        unauthenticated: 5
        time: 1